# Generated by Django 4.1.7 on 2023-04-05 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=14)),
                ('last_name', models.CharField(max_length=14)),
                ('email', models.EmailField(max_length=40)),
                ('feild_of_study', models.CharField(max_length=20)),
                ('gpa', models.FloatField()),
            ],
        ),
    ]
